BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
SLEEP_LED_ENABLE = yes
NKRO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
OLED_DRIVER_ENABLE = yes
ENCODER_ENABLE = no

DEFAULT_FOLDER = daverichmond/macro16/bluepill
